### ISSUE TITLE
Cannot retrieve or change state (eg, cannot turn light on)

### ISSUE THREAD

**Issue by warlordz520** [domness/ha_glowdreaming#3]
App on phone able to control Glow Sleep Easy but in Home Assistant, gets below error when trying to turn Glow Sleep Easy light on/off

2025-06-22 21:32:19.276 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140626536881392] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2794, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2837, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 648, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1703, in async_turn_on
    await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1699, in turn_on
    raise NotImplementedError
NotImplementedError

**Comment by domness** [comment]
@warlordz520 This is an example script I've got setup:

```
sequence:
  - action: glowdreaming.set_mode
    metadata: {}
    data:
      light_effect: None
      brightness: None
      volume: High
    target:
      device_id: 3c0430c188e092e580e712f686a09db5
alias: Set Glow Dreaming for Sleep
description: ""
```

```
sequence:
  - action: glowdreaming.set_mode
    metadata: {}
    data:
      light_effect: Sleep
      brightness: High
      volume: High
    target:
      device_id: 3c0430c188e092e580e712f686a09db5
alias: Set Glow Dreaming to night change (red, noise)
description: ""
```
